### ISSUE TITLE
Markers represented in IIIF manifest

### ISSUE THREAD

**Issue by stephenwf** [digirati-co-uk/timeliner#191]
With the addition of a new type in our range model, we need a way to temporally target a single timestamp in a range. @tomcrane you may be able to help us fit this into the existing model.

**Comment by tomcrane** [comment]
I think this would work using a PointSelector - see the P3 documentation for `start`:

https://preview.iiif.io/api/image-prezi-rc2/api/presentation/3.0/#start

```
{
    "type": "SpecificResource",
    "source": "https://example.org/iif/1/canvas/1",
    "selector": {
      "type": "PointSelector",
      "t": 14.5
    }
}
```

This same SpecificResource would work as the target of an annotation on a point (rather than a time range) on the timeline.

Background - the reason why we can't just use the regular syntax like t=10,20 and just say t=10 is that in the media fragments spec, t=10 effectively means t=10,end - which is not what we want to say.

**Comment by stephenwf** [comment]
For reference: #1387
