### ISSUE TITLE
Report Error when saving returns non-200 message

### ISSUE THREAD

**Issue by mcwhitaker** [digirati-co-uk/timeliner#283]
This was brought up in our meeting on 3/13. When saving and Avalon timeline, if the Avalon app returns anything other than a 200, we want the user to know that saving did not succeed.

**Comment by cjcolvar** [comment]
@mcwhitaker Avalon team can handle this one too.

**Comment by joncameron** [comment]
Displaying a flash message to the user indicating an error and that their timeline was not saved successfully would be ideal. We also discussed removing the checkmark animation that occurs when the save button is clicked, since it's tied to the click event rather than to the success of the system action.

**Comment by bkeese** [comment]
This was fixed with https://github.com/IUBLibTech/timeliner/pull/15
